name: Deploy EC2 Instance with CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy EC2 with CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name simple-ec2-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides KeyName=${{ secrets.KEY_NAME }}

      - name: Obtener IP pública de la instancia
        id: get_ip
        run: |
          IP=$(aws cloudformation describe-stacks --stack-name simple-ec2-stack --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" --output text)
          echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Mostrar IP pública
        run: echo "La IP pública de la instancia EC2 es $EC2_PUBLIC_IP"
